In [70]:
import pandas as pd

In [71]:
# Read in data
df = pd.read_csv('GSL_drainage_basin_dataset.csv', index_col=0)
# Use datetime as index
df.index = pd.to_datetime(df.index)

In [72]:
# Aggregate by month
monthly_df = df.groupby(pd.Grouper(freq='SM')).mean()
monthly_df.index = monthly_df.index.strftime('up to %Y-%m-%d')
# Drop cols that are all NaNs
monthly_df = monthly_df.dropna('columns', how='all')

In [73]:
# Which rows have very little data?
monthly_df.index[monthly_df.isna().sum(axis=1) > len(monthly_df.columns)-5]

Index(['1847-10', '1847-11', '1847-12', '1848-01', '1848-02', '1848-03',
       '1848-04', '1848-05', '1848-06', '1848-07',
       ...
       '1892-03', '1892-04', '1892-05', '1892-06', '1892-07', '1892-08',
       '1892-09', '1892-10', '1892-11', '1892-12'],
      dtype='object', length=543)

In [74]:
# Looks like we should start in 1893
monthly_df = monthly_df[1086:-2]
monthly_df

,PRCP,SNOW,SNWD,PRCP_US1UTBE0002,SNOW_US1UTBE0002,SNWD_US1UTBE0002,PRCP_US1UTBE0003,SNOW_US1UTBE0003,SNWD_US1UTBE0003,PRCP_US1UTBE0004,...,TMIN_USW00024193,TMAX_USW00024193,PRCP_USW00053167,TMIN_USW00053167,TMAX_USW00053167,PRCP_USW00094097,SNWD_USW00094097,TMIN_USW00094097,TMAX_USW00094097,depth
1893-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4201.700000
1893-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4201.900000
1893-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4202.000000
1893-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4202.400000
1893-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4202.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11,12.200000,3.080000,51.00,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.966667,NaN,-50.566667,92.800000,4192.176667
2020-12,7.612903,6.161290,45.70,7.785714,8.25,120.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.096774,NaN,-124.096774,4.419355,4192.190323
2021-01,12.483871,5.928571,42.75,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.483871,NaN,-102.677419,4.935484,4192.303571
2021-02,0.000000,0.000000,NaN,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.214286,NaN,-55.964286,33.107143,NaN
2021-03,NaN,NaN,NaN,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,-85.000000,63.500000,NaN

In [75]:
# Do the endpoints have enough data?
monthly_df.iloc[0].dropna()

PRCP_USC00422696      13.133333
SNOW_USC00422696      10.645161
TMIN_USC00422696     -79.451613
TMAX_USC00422696      15.161290
PRCP_USC00423353     164.000000
SNOW_USC00423353      89.000000
TMIN_USC00423353    -154.645161
TMAX_USC00423353     -91.000000
PRCP_USC00423671     114.500000
SNOW_USC00423671      82.500000
PRCP_USC00425183      55.000000
SNOW_USC00425183       4.483871
TMIN_USC00425183    -110.633333
TMAX_USC00425183      25.800000
PRCP_USC00425963      80.333333
SNOW_USC00425963      25.000000
SNOW_USC00427927       7.387097
TMIN_USC00427927    -139.225806
TMAX_USC00427927       3.290323
depth               4201.700000
Name: 1893-01, dtype: float64

In [76]:
monthly_df.iloc[-1].dropna()

PRCP_US1UTBE0002      0.0
SNOW_US1UTBE0002      0.0
PRCP_US1UTBE0005      0.0
SNOW_US1UTBE0005      0.0
PRCP_US1UTBE0006      0.0
                    ...
TMIN_USW00024126    -38.5
TMAX_USW00024126    108.0
PRCP_USW00094097      0.0
TMIN_USW00094097    -85.0
TMAX_USW00094097     63.5
Name: 2021-03, Length: 361, dtype: float64

In [78]:
# Yep looks good! Saving to csv
monthly_df.to_csv('GSL_semi_monthly.csv')